version: 2
jobs:
  build:
    working_directory: ~/igc
    docker:
      - image: balexand/elixir:otp-20.0-elixir-1.5.1

    steps:
      - checkout
      - run: mix deps.get
      - run: MIX_ENV=test mix test
