version: 2
jobs:
  build:
    working_directory: ~/igc
    docker:
      - image: circleci/elixir:1.5

    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force

      - run: mix deps.get
      - run: MIX_ENV=test mix test
